[project]
name = "bosh"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lark>=1.3.1",
]

[tool.uv]
package = true

[dependency-groups]
dev = [
    "auto-py-to-exe>=2.50.1",
    "pytest>=9.0.3",
]

[project.scripts]
bosh = "bosh.app.bosh:main"
build = "scripts.build:build"
exe = "scripts.build_exe:build_exe"
