?start: program

program: block

block: _SEP* stmt (_SEP+ stmt)* _SEP*
?in_code_block: _NL* _BLOCKSTART _NL*  block _NL* _BLOCKEND


?stmt   : general_stmt
        | domain_stmt
        | def_stmt


?general_stmt   : "if" expr ":"? in_code_block ("~" _NL* ( "else"|"otherwise") ":"?  in_code_block)?  -> if_else
                | stmt ("else" | "otherwise") stmt                              -> if_unable
                | ("for all" | "for each") IDENT "in" expr? ":"? in_code_block  -> for_all
                | "repeat until" expr ":"?  in_code_block                       -> repeat
                | "count" IDENT? "from" expr "to" expr ":"? in_code_block       -> count
                | ("stop" | "quit")                                             -> quit
                | ("say" | "print" | "output") expr                             -> print
                | "return" expr?                                                -> return_
                | "continue"                                                    -> continue_
                | "break"                                                       -> break_
                | term "at" "index"? plus_expr "is" expr                        -> assign_to_list
                | INSERT expr "to" term ("at" "index"? expr)?                   -> add_to_list
                | "remove" expr "from" expr                                     -> remove_from_list
                | "remove index" expr "from" expr                               -> remove_from_list_at
                | ( "run" | "call" ) IDENT ("using" "(" expr ("," expr)* ")")?  -> call_func
INSERT : "append" | "prepend" | "insert"

?def_stmt       : IDENT "is" expr               -> assign
                | IDENT "is" "a" TYPE expr?     -> assign_type
                | "new"? ( "task" | "function" ) IDENT ("uses" "(" (IDENT ("," IDENT)*)? ")")? ":"? in_code_block -> assign_func


?domain_stmt    : ("make " | "create ") NEW? PATH expr ("in" expr)? -> make
                | "go to" expr                  -> go_to
                | "rename" expr "to" expr       -> rename
                | "delete" expr                 -> delete
                | "copy from" expr "to" expr    -> copy_from_to
                | "go up"                       -> go_up
                | "move" expr "to" expr         -> move

                | "write" expr "to" expr        -> write
                | "execute" expr                -> execute
                | "pause"                       -> pause
                | "wait" expr                   -> wait


?expr   : or_expr
        | "read" expr                   -> read

?or_expr    : and_expr
            | or_expr ( "||"  | "or" ) and_expr  -> or_

?and_expr   : eq_expr
            | and_expr ( "&&"  | "and" ) eq_expr -> and_

?eq_expr    : rel_expr
            | eq_expr  ( "==" | "equals" | "is" )      rel_expr         -> eq
            | eq_expr  ( "!=" | "not equals" | "is not" )  rel_expr     -> neq
            | rel_expr "is a" ( TYPE | PATH )                           -> eq_type
            | rel_expr "is not a" ( TYPE | PATH )                       -> neq_type

?rel_expr   : plus_expr
            | rel_expr ( ">"  | "greater than" ) plus_expr              -> gt
            | rel_expr ( "<"  | "less than" ) plus_expr                 -> lt
            | rel_expr ( ">=" | "greater or equal than" ) plus_expr     -> goet
            | rel_expr ( "<=" | "less or equal than" ) plus_expr        -> loet
            | access_expr "regex" access_expr                           -> regex
            | access_expr "starts with" access_expr                     -> starts_with
            | access_expr "ends with" access_expr                       -> ends_with
            | access_expr "contains" access_expr                        -> contains

?plus_expr  : mult_expr
            | plus_expr ( "+" | "plus" ) mult_expr       -> plus
            | plus_expr ( "-" | "minus" ) mult_expr      -> minus

?mult_expr  : unary_expr
            | mult_expr ( "*" | "times" ) unary_expr            -> mult
            | mult_expr ( "/" | "divided by" ) unary_expr       -> div
            | mult_expr ( "%" | "mod" ) unary_expr              -> mod

?unary_expr : pow_expr
            | ( "not" | "!" ) unary_expr                -> not_
            | ( "negative" | "neg" | "-" ) unary_expr   -> neg
            | "floor of" pow_expr                       -> floor
            | "ceiling of" pow_expr                     -> ceiling
            | "round of" pow_expr                       -> round

?pow_expr   : access_expr
            | pow_expr ( "^" | "pow" | "to the power of" ) access_expr  -> pow
            | ( "sqrt" | "square root of" ) access_expr                 -> sqrt

?access_expr    : term
                | access_expr "at" "index"? term        -> list_look
                | "letter" term "of" term               -> text_look
                | "length of" term                      -> length
                | "first" "element"? "of" term          -> first
                | "last" "element"? "of"  term          -> last
                | access_expr "age"                     -> age
                | access_expr "name"                    -> file_name
                | access_expr unit                      -> unit
                | access_expr "as" TYPE                 -> type_cast
                | "random from" expr "to" expr          -> random


?term   : IDENT "result" ("using" "(" expr ("," expr)* ")")? -> func
        | text
        | date
        | IDENT                         -> var
        | NUMBER                        -> number
        | FLOAT                         -> decimal
        | BOOLEAN                       -> boolean
        | "[" term ("," term)* "]"      -> list
        | "input" (expr)?               -> input
        | "null"                        -> null
        | "now"                         -> now
        | "here"                        -> here
        | "(" expr ")"                  -> paren
        | TYPE


TYPE    : ("text" | "string")
        | ("int" | "number")
        | ("float" | "decimal")
        | ("boolean" | "bool")
        | "date"
        | "time" 
        | "list"


unit    : ("second" | "seconds")        -> second
        | ("minute" | "minutes")        -> minute
        | ("hour" | "hours")            -> hour
        | ("day" | "days")              -> day
        | ("month" | "months")          -> month
        | ("year" | "years")            -> year


text: "\"" (str_chars | interp)* "\""
str_chars: /([^"{\\]|\\.)+/
interp: "{" expr "}"

date: "t"/[0-9]{4}-[0-1][0-9]-[0-3][0-9]( [0-2][0-9]:[0-5][0-9]:[0-5][0-9](\.[0-9]{0,6})?)?/

FLOAT: /[0-9]+\.[0-9]+/

PATH: "file" | "folder"
NEW : "new"
_BLOCKSTART: "{"
_BLOCKEND: "}" 
_SEP: "." _WS* _NL* | _NL+
COMMENT: /#[^\n]*\n?/
BOOLEAN: "true" | "false"
IDENT: /[A-Z][a-zA-Z0-9_]*/(" "*/[A-Z][a-zA-Z0-9_]*/)*
%import common.WS_INLINE -> _WS
%import common.NEWLINE -> _NL
%import common.INT -> NUMBER
%ignore COMMENT
%ignore _WS